[package]
name = "timeline-vis"
version = "0.1.0"
authors = ["Brian Pfretzschner <brian.pfretzschner@de.bosch.com>"]
edition = "2018"

[dependencies]
zip = "0.5"
chrono = "0.4"
geo = "0.12.2"
maplit = "1.0.2"
