[package]
name = "timeline-vis"
version = "0.1.0"
authors = ["Brian Pfretzschner <brian.pfretzschner@de.bosch.com>"]
edition = "2018"

[dependencies]
zip = "0.5"
chrono = "0.4"
serde = "~1"
serde_json = "~1"
serde_derive = "~1"
elastic = "~0.21.0-pre.5"
elastic_derive = "~0.21.0-pre.5"
